
#static is here tracker_static
#username --root
#password--###
"""
Django settings for qmpkbdb project.

Generated by 'django-admin startproject' using Django 1.8.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import django.conf import settings

if not seetings.DEBUG:
	import os
	import smtplib
	from .store_password import *

	BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

	# Quick-start development settings - unsuitable for production
	# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

	# SECURITY WARNING: keep the secret key used in production secret!
	SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY',SECRET_KEY)
	# SECURITY WARNING: don't run with debug turned on in production!
	DEBUG = bool(os.environ.get("DJANGO_DEBUG",False))
	#DEBUG404 = True
	
	ADMINS =(
				('qmpkb','qmpkb@gmail.com'),
			)

	ALLOWED_HOSTS = ['*',u'pallab-precision-workstation-t7500'] # place qmpkb domain when it is live
	EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
	DEFAULT_FROM_EMAIL = DEFAULT_FROM_EMAIL
	EMAIL_HOST=EMAIL_HOST
	EMAIL_HOST_USER=EMAIL_HOST_USER
	EMAIL_HOST_PASSWORD=EMAIL_HOST_PASSWORD
	EMAIL_PORT=587
	EMAIL_USE_TLS=True
	EMAIL_DEBUG = False


	# Application definition

	INSTALLED_APPS = (
	    'django.contrib.admin',
	    'django.contrib.auth',
	    'django.contrib.contenttypes',
	    'django.contrib.sessions',
	    'django.contrib.sites',
	    'django.contrib.messages',
	    'django.contrib.staticfiles',
	    #own app
	    'qmpkbapp',
	    #3rd party app
	    'rest_framework',
	    'rest_framework_swagger',
	    'crispy_forms',
	)

	REST_FRAMEWORK = {
	    # Parser classes priority-wise for Swagger
	    'DEFAULT_PARSER_CLASSES': [
	        'rest_framework.parsers.JSONParser',
	    ],
	    'DEFAULT_RENDERER_CLASSES': [
	        'rest_framework.renderers.JSONRenderer',
	    ],
	}

	SWAGGER_SETTINGS = {

	    # For using other mechanisms for authentication ('basic' uses username/password)
	    'SECURITY_DEFINITIONS': None,
	    'DOC_EXPANSION': None,

	    # For validating your swagger schema(setting None to not validate)
	    'VALIDATOR_URL': None,
	}
	MIDDLEWARE = (
	    'django.contrib.sessions.middleware.SessionMiddleware',
	    'django.middleware.common.CommonMiddleware',
	    'django.middleware.csrf.CsrfViewMiddleware',
	    'django.contrib.auth.middleware.AuthenticationMiddleware',
	    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	    'django.contrib.messages.middleware.MessageMiddleware',
	    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	    'django.middleware.security.SecurityMiddleware',
	    #my middleware
	    #'qmpkbapp.middleware.restrictstafftoadminmiddleware.RestrictStaffToAdminMiddleware',
	)

	ROOT_URLCONF = 'qmkbdjangulardb.urls'

	TEMPLATES = [
	    {
	        'BACKEND': 'django.template.backends.django.DjangoTemplates',
	        'DIRS': [os.path.join(BASE_DIR, "templates")],
	        'APP_DIRS': True,
	        'OPTIONS': {
	            'context_processors': [
	                'django.template.context_processors.debug',
	                'django.template.context_processors.request',
	                'django.contrib.auth.context_processors.auth',
	                'django.contrib.messages.context_processors.messages',
	            ],
	        },
	    },
	]

	WSGI_APPLICATION = 'qmkbdjangulardb.wsgi.application'
	SESSION_ENGINE = "django.contrib.sessions.backends.file"

	# Internationalization
	# https://docs.djangoproject.com/en/1.8/topics/i18n/

	DATABASES = {
	    'default': {
	        'ENGINE': 'django.db.backends.sqlite3',
	        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	    }
	}


	# Internationalization
	# https://docs.djangoproject.com/en/1.8/topics/i18n/

	LANGUAGE_CODE = 'en-us'

	TIME_ZONE = 'America/Vancouver'

	USE_I18N = True

	USE_L10N = True

	USE_TZ = True


	# Static files (CSS, JavaScript, Images)
	# https://docs.djangoproject.com/en/1.8/howto/static-files/

	STATIC_URL = '/static/'
	STATIC_ROOT =  os.path.join(os.path.dirname(BASE_DIR), 'static-root', 'ang')
	STATICFILES_DIRS = (
	    os.path.join(BASE_DIR, 'static'),
	    #'/var/www/static/',
	)

	MEDIA_URL='/media/'
	MEDIA_ROOT= os.path.join(os.path.dirname(BASE_DIR), 'static-root', 'media_root')

	# files for JSON
	FILE_URL = '/resultFile/'
	FILE_ROOT= os.path.join(BASE_DIR, 'resultFile')
	# crispy forms tag settings
	CRISPY_TEMPLATE_PACK ='bootstrap3'

	# django redux registration seetings
	ACCOUNT_ACTIVATION_DAYS= 1 # email activated for 1 day
	REGISTRATION_AUTO_LOGIN= True
	# REGISTRATION_EMAIL_HTML = False
	SITE_ID=1
	#logout user after browser close
	SESSION_EXPIRE_AT_BROWSER_CLOSE = True

	#delete after publication
	LOGIN_REDIRECT_URL='/'