# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddressInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=1200)),
                ('access_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
